package no.anksoft.pginmem

import no.anksoft.pginmem.statements.*
import org.slf4j.LoggerFactory
import java.io.InputStream
import java.io.Reader
import java.math.BigDecimal
import java.net.URL
import java.sql.*
import java.sql.Date
import java.util.*

private fun splitStringToWords(sql:String):List<String> {
    val result:MutableList<String> = mutableListOf()
    val trimmed = sql.toLowerCase().trim().replace("\n"," ")
    var index = 0
    var previndex = 0
    while (index < trimmed.length) {
        val charAtPos:Char = trimmed[index]

        if ((charAtPos.isWhitespace())) {
            if (index > previndex) {
                result.add(trimmed.substring(previndex,index))
            }
            index++
            previndex = index
            continue
        }
        if ((charAtPos == '(') || (charAtPos == ')') || (charAtPos == ',')) {
            if (index > previndex) {
                result.add(trimmed.substring(previndex,index))
            }
            result.add(trimmed.substring(index,index+1))
            index++
            previndex=index
            continue
        }
        index++
    }
    if (index > previndex) {
        result.add(trimmed.substring(previndex,index))
    }
    return result
}

private val logger = LoggerFactory.getLogger(DbPreparedStatement::class.java)

/*
private val x =
bool,B
bytea,U
char,S
name,S
int8,N
int2,N
int2vector,A
int4,N
regproc,N
text,S
oid,N
tid,U
xid,U
cid,U
oidvector,A
json,U
xml,U
pg_node_tree,S
pg_ndistinct,S
pg_dependencies,S
pg_ddl_command,P
smgr,U
point,G
lseg,G
path,G
box,G
polygon,G
line,G
float4,N
float8,N
abstime,D
reltime,T
tinterval,T
unknown,X
circle,G
money,N
macaddr,U
inet,I
cidr,I
macaddr8,U
aclitem,U
bpchar,S
varchar,S
date,D
time,D
timestamp,D
timestamptz,D
interval,T
timetz,D
bit,V
varbit,V
numeric,N
refcursor,U
regprocedure,N
regoper,N
regoperator,N
regclass,N
regtype,N
regrole,N
regnamespace,N
uuid,U
pg_lsn,U
tsvector,U
gtsvector,U
tsquery,U
regconfig,N
regdictionary,N
jsonb,U
txid_snapshot,U
int4range,R
numrange,R
tsrange,R
tstzrange,R
daterange,R
int8range,R
record,P
cstring,P
any,P
anyarray,P
void,P
trigger,P
event_trigger,P
language_handler,P
internal,P
opaque,P
anyelement,P
anynonarray,P
anyenum,P
fdw_handler,P
index_am_handler,P
tsm_handler,P
anyrange,P
*/

fun createPreparedStatement(sql:String,dbTransaction: DbTransaction):DbPreparedStatement {
    logger.debug("Called $sql")
    val words:List<String> = splitStringToWords(sql)
    when {
        sql.toLowerCase().startsWith("select t.table_name from information_schema.tables") -> return StatementToReturnFixed(emptyList())
        sql.toLowerCase().startsWith("select relname from pg_catalog.pg_class") -> return StatementToReturnFixed(emptyList())
        sql.toLowerCase().startsWith("select exists (") -> return StatementToReturnFixed(listOf(listOf(Pair("",false))))
        //sql.toLowerCase().startsWith("select count(*) from pg_namespace") -> return MockCountStatement(1)
        sql.toLowerCase().startsWith("select count(*) from pg_namespace") -> return StatementToReturnFixed(listOf(listOf(Pair("",1))))
        sql.toLowerCase().startsWith("select set_config") -> return NoopStatement()
        sql.toLowerCase().startsWith("set role") -> return NoopStatement()
        sql.toLowerCase() == "select current_schema" -> return SelectOneValueStatement("public")
        sql.toLowerCase() == "select current_user" -> return SelectOneValueStatement("user")
        sql.toLowerCase() == "select version()" -> return SelectOneValueStatement("PostgreSQL 10.6 Pginmemver")
        sql.toLowerCase() == "show search_path" -> return SelectOneValueStatement("\"\$user\", public")
        words.size >= 2 && words[0] == "create" && words[1] == "table" -> return CreateTableStatement(words,dbTransaction)
        words.size >= 2 && words[0] == "insert" && words[1] == "into" -> return InsertIntoStatement(words,dbTransaction)
        words.isNotEmpty() && words[0] == "select" -> return SelectStatement(words,dbTransaction)
        words.isNotEmpty() && words[0] == "update" -> return UpdateStatement(words,dbTransaction)
        else -> throw SQLException("Unknown statement $sql")
    }
}

abstract class DbPreparedStatement:PreparedStatement {
    private val logger = LoggerFactory.getLogger(this::class.java)
    override fun <T : Any?> unwrap(iface: Class<T>?): T {
        TODO("Not yet implemented")
    }

    override fun isWrapperFor(iface: Class<*>?): Boolean {
        TODO("Not yet implemented")
    }

    override fun close() {

    }

    override fun executeQuery(): ResultSet {
        TODO("Not yet implemented")
    }

    override fun executeQuery(sql: String?): ResultSet {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(): Int {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(sql: String?): Int {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(sql: String?, autoGeneratedKeys: Int): Int {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(sql: String?, columnIndexes: IntArray?): Int {
        TODO("Not yet implemented")
    }

    override fun executeUpdate(sql: String?, columnNames: Array<out String>?): Int {
        TODO("Not yet implemented")
    }

    override fun getMaxFieldSize(): Int {
        TODO("Not yet implemented")
    }

    override fun setMaxFieldSize(max: Int) {
        TODO("Not yet implemented")
    }

    override fun getMaxRows(): Int {
        TODO("Not yet implemented")
    }

    override fun setMaxRows(max: Int) {
        logger.warn("Base setMaxRows $max")
    }

    override fun setEscapeProcessing(enable: Boolean) {
        logger.warn("Base setEscapeProcessing $enable")
    }

    override fun getQueryTimeout(): Int {
        TODO("Not yet implemented")
    }

    override fun setQueryTimeout(seconds: Int) {
        logger.warn("Base setQueryTimeout $seconds")

    }

    override fun cancel() {
        logger.warn("Base cancel")
    }

    override fun getWarnings(): SQLWarning {
        TODO("Not yet implemented")
    }

    override fun clearWarnings() {
        logger.warn("Base clearWarnings")
    }

    override fun setCursorName(name: String?) {
        logger.warn("Base setCursorName")
    }

    override fun execute(): Boolean {
        TODO("Not yet implemented")
    }

    override fun execute(sql: String?): Boolean {
        TODO("Not yet implemented")
    }

    override fun execute(sql: String?, autoGeneratedKeys: Int): Boolean {
        TODO("Not yet implemented")
    }

    override fun execute(sql: String?, columnIndexes: IntArray?): Boolean {
        TODO("Not yet implemented")
    }

    override fun execute(sql: String?, columnNames: Array<out String>?): Boolean {
        TODO("Not yet implemented")
    }

    override fun getResultSet(): ResultSet {
        TODO("Not yet implemented")
    }

    override fun getUpdateCount(): Int {
        TODO("Not yet implemented")
    }

    override fun getMoreResults(): Boolean {
        TODO("Not yet implemented")
    }

    override fun getMoreResults(current: Int): Boolean {
        TODO("Not yet implemented")
    }

    override fun setFetchDirection(direction: Int) {
        logger.warn("Base setFetchDirection $direction")
    }

    override fun getFetchDirection(): Int {
        TODO("Not yet implemented")
    }

    override fun setFetchSize(rows: Int) {
        logger.warn("Base setFetchSize $rows")
    }

    override fun getFetchSize(): Int {
        TODO("Not yet implemented")
    }

    override fun getResultSetConcurrency(): Int {
        TODO("Not yet implemented")
    }

    override fun getResultSetType(): Int {
        TODO("Not yet implemented")
    }

    override fun addBatch() {
        logger.warn("Base addBatch")

    }

    override fun addBatch(sql: String?) {
        logger.warn("Base $sql")
    }

    override fun clearBatch() {
        logger.warn("Base clearBatch")
    }

    override fun executeBatch(): IntArray {
        TODO("Not yet implemented")
    }

    override fun getConnection(): Connection {
        TODO("Not yet implemented")
    }

    override fun getGeneratedKeys(): ResultSet {
        TODO("Not yet implemented")
    }

    override fun getResultSetHoldability(): Int {
        TODO("Not yet implemented")
    }

    override fun isClosed(): Boolean {
        TODO("Not yet implemented")
    }

    override fun setPoolable(poolable: Boolean) {
        logger.warn("Base setPoolable $poolable")
    }

    override fun isPoolable(): Boolean {
        TODO("Not yet implemented")
    }

    override fun closeOnCompletion() {
        logger.warn("Base closeOnCompletion")
    }

    override fun isCloseOnCompletion(): Boolean {
        TODO("Not yet implemented")
    }

    override fun setNull(parameterIndex: Int, sqlType: Int) {
        logger.warn("Base setNull $parameterIndex $sqlType")
    }

    override fun setNull(parameterIndex: Int, sqlType: Int, typeName: String?) {
        logger.warn("Base setNull")
    }

    override fun setBoolean(parameterIndex: Int, x: Boolean) {
        logger.warn("Base setBoolean")
    }

    override fun setByte(parameterIndex: Int, x: Byte) {
        logger.warn("Base setByte")
    }

    override fun setShort(parameterIndex: Int, x: Short) {
        logger.warn("Base setShort")
    }

    override fun setInt(parameterIndex: Int, x: Int) {
        logger.warn("Base setInt")
    }

    override fun setLong(parameterIndex: Int, x: Long) {
        logger.warn("Base setLong")
    }

    override fun setFloat(parameterIndex: Int, x: Float) {
        logger.warn("Base setFloat")
    }

    override fun setDouble(parameterIndex: Int, x: Double) {
        logger.warn("Base setDouble")
    }

    override fun setBigDecimal(parameterIndex: Int, x: BigDecimal?) {
        logger.warn("Base setBigDecimal")
    }

    override fun setString(parameterIndex: Int, x: String?) {
        logger.warn("Base setString")
    }

    override fun setBytes(parameterIndex: Int, x: ByteArray?) {
        logger.warn("Base setBytes")
    }

    override fun setDate(parameterIndex: Int, x: Date?) {
        logger.warn("Base setDate")
    }

    override fun setDate(parameterIndex: Int, x: Date?, cal: Calendar?) {
        logger.warn("Base setDate")
    }

    override fun setTime(parameterIndex: Int, x: Time?) {
        logger.warn("Base setTime")
    }

    override fun setTime(parameterIndex: Int, x: Time?, cal: Calendar?) {
        logger.warn("Base setTime")
    }

    override fun setTimestamp(parameterIndex: Int, x: Timestamp?) {
        logger.warn("Base setTimestamp")
    }

    override fun setTimestamp(parameterIndex: Int, x: Timestamp?, cal: Calendar?) {
        logger.warn("Base setTimestamp")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?, length: Int) {
        logger.warn("Base setAsciiStream")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?, length: Long) {
        logger.warn("Base setAsciiStream")
    }

    override fun setAsciiStream(parameterIndex: Int, x: InputStream?) {
        logger.warn("Base setAsciiStream")
    }

    override fun setUnicodeStream(parameterIndex: Int, x: InputStream?, length: Int) {
        logger.warn("Base setUnicodeStream")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?, length: Int) {
        logger.warn("Base setBinaryStream")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?, length: Long) {
        logger.warn("Base setBinaryStream")
    }

    override fun setBinaryStream(parameterIndex: Int, x: InputStream?) {
        logger.warn("Base setBinaryStream")
    }

    override fun clearParameters() {
        logger.warn("Base clearParameters")
    }

    override fun setObject(parameterIndex: Int, x: Any?, targetSqlType: Int) {
        logger.warn("Base setObject")
    }

    override fun setObject(parameterIndex: Int, x: Any?) {
        logger.warn("Base setObject")
    }

    override fun setObject(parameterIndex: Int, x: Any?, targetSqlType: Int, scaleOrLength: Int) {
        logger.warn("Base setObject")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?, length: Int) {
        logger.warn("Base setCharacterStream")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?, length: Long) {
        logger.warn("Base setCharacterStream")
    }

    override fun setCharacterStream(parameterIndex: Int, reader: Reader?) {
        logger.warn("Base setCharacterStream")
    }

    override fun setRef(parameterIndex: Int, x: Ref?) {
        logger.warn("Base setRef")
    }

    override fun setBlob(parameterIndex: Int, x: Blob?) {
        logger.warn("Base setBlob")
    }

    override fun setBlob(parameterIndex: Int, inputStream: InputStream?, length: Long) {
        logger.warn("Base setBlob")
    }

    override fun setBlob(parameterIndex: Int, inputStream: InputStream?) {
        logger.warn("Base setBlob")
    }

    override fun setClob(parameterIndex: Int, x: Clob?) {
        logger.warn("Base setClob")
    }

    override fun setClob(parameterIndex: Int, reader: Reader?, length: Long) {
        logger.warn("Base setClob")
    }

    override fun setClob(parameterIndex: Int, reader: Reader?) {
        logger.warn("Base setClob")
    }

    override fun setArray(parameterIndex: Int, x: java.sql.Array?) {
        logger.warn("Base setArray")
    }

    override fun getMetaData(): ResultSetMetaData {
        TODO("Not yet implemented")
    }

    override fun setURL(parameterIndex: Int, x: URL?) {
        logger.warn("Base setURL")
    }

    override fun getParameterMetaData(): ParameterMetaData {
        TODO("Not yet implemented")
    }

    override fun setRowId(parameterIndex: Int, x: RowId?) {
        logger.warn("Base setRowId")
    }

    override fun setNString(parameterIndex: Int, value: String?) {
        logger.warn("Base setNString")
    }

    override fun setNCharacterStream(parameterIndex: Int, value: Reader?, length: Long) {
        logger.warn("Base setNCharacterStream")
    }

    override fun setNCharacterStream(parameterIndex: Int, value: Reader?) {
        logger.warn("Base setNCharacterStream")
    }

    override fun setNClob(parameterIndex: Int, value: NClob?) {
        logger.warn("Base setNClob")
    }

    override fun setNClob(parameterIndex: Int, reader: Reader?, length: Long) {
        logger.warn("Base setNClob")
    }

    override fun setNClob(parameterIndex: Int, reader: Reader?) {
        logger.warn("Base setNClob")
    }

    override fun setSQLXML(parameterIndex: Int, xmlObject: SQLXML?) {
        logger.warn("Base setSQLXML")
    }


}